# `minigrep` CI GitHub Action. Built using the following sources:
#    - Default rust runnner configured by GitHub
#    - actions-rs meta: https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
#      note: actions-rs removed due to lack of maintenance and warnings being thrown, but the
#      structure and principles the examples provide remain.

name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check
        run: cargo check
          
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Tests
        run: cargo test --verbose

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Rustfmt
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clippy
        run: cargo clippy -- -D warnings
